apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ansible
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjoKICAgIHsKICAgICAgICAiZ2hjci5pbyI6CiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJhdXRoIjoiYlhKcGVtdHBjSEp0YmpwbmFIQmZRak5xTVVFd2MzZDBSMlp6TTJKV1dsRnhZMWxJT1doUGNEZENNVmxDTkRSVFRXWjIiCiAgICAgICAgICAgIH0KICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
  namespace: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ansible
          image: ghcr.io/mrizkiprmn/ansible-example:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ansible
  namespace: ansible
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80