---
  - hosts: localhost
    vars: 
      hub: "mrizkiprmn"
      proj: "php"
      tag: "latest"
      dests: /home/ubuntu/github/php
      repo: https://github.com/mrizkiprmn/php-example.git
      default_container_name: ansible

    tasks:

      - name: "Check connection"
        ping:

      - name: "Esnure git installed"
        apt:
          name: git
          state: present

      - name: "Installing python docker"
        pip:
          name: 
          - docker
          - docker-compose


      - name: "Git clone"
        git:
          repo: "{{repo}}"
          dest: "{{dests}}/{{proj}}"


      - name: "Build image"
        docker_image:
          name: "{{hub}}/{{proj}}:{{tag}}"
          build:
            path: "{{dests}}/{{proj}}"
          source: build


      - name: "Push image to registry"
        docker_image:
          name: "{{hub}}/{{proj}}:{{tag}}"
          repository: "{{hub}}/{{proj}}:{{tag}}"
          push: yes
          source: local

      - name: "Push images with command"
        command: docker push "{{hub}}/{{proj}}:{{tag}}"


      - name: "Remove image"
        docker_image:
          state: absent
          name: "{{hub}}/{{proj}}"
          tag: "{{tag}}"
          force_tag: yes


      - name: "Pull images"
        docker_image:
          name: "{{hub}}/{{proj}}:{{tag}}"
          source: pull


      - name: "Running Docker Container"
        docker_container:
          name: "{{default_container_name}}"
          image: "{{hub}}/{{proj}}:{{tag}}"
          state: started
          restart_policy: always
          ports:
            - "80:80"

      - name: "Deploy Docker Compose stack"
        docker_compose:
          project_src: "{{dests}}"
          files:
            - docker-compose.yaml