---
  - hosts: localhost
    connection: local

    vars: 
      hub: "mrizkiprmn"
      proj: "php"
      tag: "latest"
      dir: /home/mrizkiprmn/Documents/github
      repo: https://github.com/mrizkiprmn/ansible-example.git
      container_name: ansible

    pre_tasks:
  
      - name: install pre-requisites
        pip:
          name: 
          - docker
          - docker-compose

    tasks:

      - name: build image
        docker_image:
          name: "{{hub}}/{{proj}}:{{tag}}"
          build:
            path: "{{dir}}/{{proj}}"
          source: build


      - name: push image to registry
        docker_image:
          name: "{{hub}}/{{proj}}:{{tag}}"
          repository: "{{hub}}/{{proj}}:{{tag}}"
          push: yes
          source: local


      - name: remove image unused
        docker_image:
          state: absent
          name: "{{hub}}/{{proj}}"
          tag: "{{tag}}"
          force_tag: yes


      - name: pull images
        docker_image:
          name: "{{hub}}/{{proj}}:{{tag}}"
          source: pull


      - name: running Docker Container
        docker_container:
          name: "{{container_name}}"
          image: "{{hub}}/{{proj}}:{{tag}}"
          state: started
          restart_policy: always
          ports:
            - "80:80"

      - name: deploy docker-compose
        docker_compose:
          project_src: "{{dir}}"
          files:
            - docker-compose.yaml